const AUTH_ACTION_TYPES ={
    LOGIN_REQUEST: 'LOGIN REQUEST',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    REFRESH_REQUSET: 'REFRESH_REQUSET',

    AUTH_REQUSET: 'AUTH_REQUEST',
    AUTH_REQUSET_SUCCESS: 'AUTH_REQUEST_SUCCESS',
    AUTH_REQUSET_FAILED: 'AUTH_REQUEST_FAILED',
};
export default AUTH_ACTION_TYPES;